export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const COL_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const COL_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const COL_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const ITEM_BOIS_BON = "ITEM_BOIS_BON";
export const ITEM_BOIS_DEVIS = "ITEM_BOIS_DEVIS";

export const USER_LOGOUT = "USER_LOGOUT";
export const RESET_BON = "RESET_BON";
export const RESET_DEVIS = "RESET_DEVIS";
export const RESET_TICKET = "RESET_TICKET";
export const ITEM_TICKET_BON = "ITEM_TICKET_BON";
